{{- $fullName := include "library-chart.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "library-chart.fullname" . }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
spec:
  {{- if .Values.global.suspend }}
  replicas: 0
  {{- else}}
  replicas: 1
  {{- end}}
  selector:
    matchLabels:
      {{- include "library-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "library-chart.selectorLabels" . | nindent 8 }}
    spec:
      subdomain: {{ include "library-chart.fullname" . }}
      hostname: terria-map-viewer
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.service.image.version }}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.networking.service.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.networking.service.port }}
          startupProbe:
            httpGet:
              path: /
              port: {{ .Values.networking.service.port }}
            {{- toYaml .Values.startupProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
