# Default values for jupyter.

global:
  suspend: false

service:
  image:
    version: "ghcr.io/alexis-barge/veros-edito:latest"
    custom:
      enabled: false

security:
  allowlist:
    enabled: false

environment:
  user: onyxia
  group: users

nameOverride: ""
fullnameOverride: ""

podSecurityContext:
  fsGroup: 100

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

networking:
  type: ClusterIP
  clusterIP: None
  service:
    port: 3001
  user:
    enabled: false

ingress:
  enabled: false
  tls: true
  annotations: []
    # kubernetes.io/tls-acme: "true"
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

startupProbe:
  failureThreshold: 60
  initialDelaySeconds: 5
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 5
